export const colors = [
	"red",
	"orangered",
	"orange",
	"gold",
	"yellow",
	"yellowgreen",
	"green",
	"limegreen",
	"lime",
	"springgreen",
	"mediumspringgreen",
	"mediumseagreen",
	"seagreen",
	"mediumaquamarine",
	"aquamarine",
	"lightseagreen",
	"mediumturquoise",
	"turquoise",
	"darkturquoise",
	"deepskyblue",
	"dodgerblue",
	"royalblue",
	"blue",
	"mediumblue",
	"darkblue",
	"midnightblue",
	"navy",
	"blueviolet",
	"indigo",
	"darkorchid",
	"purple",
	"darkmagenta",
	"magenta",
	"violet",
	"mediumvioletred",
	"palevioletred",
	"deeppink",
	"hotpink",
	"lightpink",
	"pink",
	"lightcoral",
	"tomato",
	"firebrick",
	"brown",
	"indianred",
	"rosybrown",
	"sienna",
	"saddlebrown",
	"peru",
	"burlywood",
	"beige",
	"wheat",
	"sandybrown",
	"tan",
	"chocolate",
	"goldenrod",
	"darkgoldenrod",
	"darkkhaki",
	"olive",
	"olivedrab",
	"darkolivegreen",
	"darkseagreen",
	"paleturquoise",
	"cadetblue",
	"steelblue",
	"#2e3440",
	"powderblue",
	"lightblue",
	"skyblue",
	"lightskyblue",
	"cornflowerblue",
	"lavender",
	"thistle",
	"plum",
	"orchid",
	"mediumorchid",
	"mediumpurple",
	"mediumslateblue",
	"slateblue",
	"darkslateblue",
	"rebeccapurple",
	"fuchsia",
	"maroon",
	"darkred",
	"salmon",
	"darksalmon",
];

/**
 * In order to dynamically use background colors with tailwind (i.e. `bg-[${someColor}]}`) the resulting color
 * must have been loaded previously. For tailwind to do so, the resulting string must be included in the code
 * somewhere. Thats what this is: a giant string of all possible svg background colors.
 * colors: https://www.w3.org/TR/css-color-3/#svg-color
 * more about tailwinds custom colors: https://github.com/tailwindlabs/tailwindcss/discussions/11189
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars,unused-imports/no-unused-vars
const ignoreMe =
	"bg-[aliceblue] bg-[antiquewhite] bg-[aqua] bg-[aquamarine] bg-[azure] bg-[beige] bg-[bisque] bg-[black] bg-[blanchedalmond] bg-[blue] bg-[blueviolet] bg-[brown] bg-[burlywood] bg-[cadetblue] bg-[chartreuse] bg-[chocolate] bg-[coral] bg-[cornflowerblue] bg-[cornsilk] bg-[crimson] bg-[cyan] bg-[darkblue] bg-[darkcyan] bg-[darkgoldenrod] bg-[darkgray] bg-[darkgreen] bg-[darkgrey] bg-[darkkhaki] bg-[darkmagenta] bg-[darkolivegreen] bg-[darkorange] bg-[darkorchid] bg-[darkred] bg-[darksalmon] bg-[darkseagreen] bg-[darkslateblue] bg-[darkslategray] bg-[darkslategrey] bg-[darkturquoise] bg-[darkviolet] bg-[deeppink] bg-[deepskyblue] bg-[dimgray] bg-[dimgrey] bg-[dodgerblue] bg-[firebrick] bg-[floralwhite] bg-[forestgreen] bg-[fuchsia] bg-[gainsboro] bg-[ghostwhite] bg-[gold] bg-[goldenrod] bg-[gray] bg-[green] bg-[greenyellow] bg-[grey] bg-[honeydew] bg-[hotpink] bg-[indianred] bg-[indigo] bg-[ivory] bg-[khaki] bg-[lavender] bg-[lavenderblush] bg-[lawngreen] bg-[lemonchiffon] bg-[lightblue] bg-[lightcoral] bg-[lightcyan] bg-[lightgoldenrodyellow] bg-[lightgray] bg-[lightgreen] bg-[lightgrey] bg-[lightpink] bg-[lightsalmon] bg-[lightseagreen] bg-[lightskyblue] bg-[lightslategray] bg-[lightslategrey] bg-[#2e3440] bg-[lightyellow] bg-[lime] bg-[limegreen] bg-[linen] bg-[magenta] bg-[maroon] bg-[mediumaquamarine] bg-[mediumblue] bg-[mediumorchid] bg-[mediumpurple] bg-[mediumseagreen] bg-[mediumslateblue] bg-[mediumspringgreen] bg-[mediumturquoise] bg-[mediumvioletred] bg-[midnightblue] bg-[mintcream] bg-[mistyrose] bg-[c:moccasin] bg-[navajowhite] bg-[navy] bg-[oldlace] bg-[olive] bg-[olivedrab] bg-[orange] bg-[orangered] bg-[orchid] bg-[palegoldenrod] bg-[palegreen] bg-[paleturquoise] bg-[palevioletred] bg-[papayawhip] bg-[peachpuff] bg-[peru] bg-[pink] bg-[plum] bg-[powderblue] bg-[purple] bg-[red] bg-[rosybrown] bg-[royalblue] bg-[saddlebrown] bg-[salmon] bg-[sandybrown] bg-[seagreen] bg-[seashell] bg-[sienna] bg-[silver] bg-[skyblue] bg-[slateblue] bg-[slategray] bg-[slategrey] bg-[snow] bg-[springgreen] bg-[steelblue] bg-[tan] bg-[teal] bg-[thistle] bg-[tomato] bg-[turquoise] bg-[violet] bg-[wheat] bg-[white] bg-[whitesmoke] bg-[yellow] bg-[yellowgreen]";
